// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const ElNotification: typeof import('element-plus/es')['ElNotification']
}
export {}
