// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ArtifactCard: typeof import('./src/components/ArtifactCard.vue')['default']
    ArtifactEditor: typeof import('./src/components/ArtifactEditor.vue')['default']
    DataExport: typeof import('./src/components/DataExport.vue')['default']
    DropSelect: typeof import('./src/components/DropSelect.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElOptionGroup: typeof import('element-plus/es')['ElOptionGroup']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    FilterSection: typeof import('./src/components/FilterSection.vue')['default']
    ImportSection: typeof import('./src/components/ImportSection.vue')['default']
    LayoutLeft: typeof import('./src/components/LayoutLeft.vue')['default']
    LayoutRight: typeof import('./src/components/LayoutRight.vue')['default']
    PresetLoader: typeof import('./src/components/PresetLoader.vue')['default']
    RangeSlider: typeof import('./src/components/RangeSlider.vue')['default']
    SectionTitle: typeof import('./src/components/SectionTitle.vue')['default']
    SortSection: typeof import('./src/components/SortSection.vue')['default']
    TextButton: typeof import('./src/components/TextButton.vue')['default']
    ValueButton: typeof import('./src/components/ValueButton.vue')['default']
    WeightSection: typeof import('./src/components/WeightSection.vue')['default']
  }
}

export { }
