/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AffnumDistr: typeof import('./src/components/dialogs/AffnumDistr.vue')['default']
    AffnumTable: typeof import('./src/components/dialogs/AffnumTable.vue')['default']
    AlikeLocker: typeof import('./src/components/dialogs/AlikeLocker.vue')['default']
    ArtifactCard: typeof import('./src/components/widgets/ArtifactCard.vue')['default']
    ArtifactCreator: typeof import('./src/components/dialogs/ArtifactCreator.vue')['default']
    ArtifactEditor: typeof import('./src/components/dialogs/ArtifactEditor.vue')['default']
    ArtifactGenerator: typeof import('./src/components/dialogs/ArtifactGenerator.vue')['default']
    BuildEditor: typeof import('./src/components/dialogs/BuildEditor.vue')['default']
    BuildLoader: typeof import('./src/components/dialogs/BuildLoader.vue')['default']
    BuildProbs: typeof import('./src/components/dialogs/BuildProbs.vue')['default']
    CharSelect: typeof import('./src/components/widgets/CharSelect.vue')['default']
    DatabaseLoader: typeof import('./src/components/dialogs/DatabaseLoader.vue')['default']
    DefeatList: typeof import('./src/components/dialogs/DefeatList.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElOptionGroup: typeof import('element-plus/es')['ElOptionGroup']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    EquipProbs: typeof import('./src/components/dialogs/EquipProbs.vue')['default']
    ExportPreview: typeof import('./src/components/dialogs/ExportPreview.vue')['default']
    FilterSection: typeof import('./src/components/sections/FilterSection.vue')['default']
    ImportSection: typeof import('./src/components/sections/ImportSection.vue')['default']
    LayoutLeft: typeof import('./src/components/layouts/LayoutLeft.vue')['default']
    LayoutRight: typeof import('./src/components/layouts/LayoutRight.vue')['default']
    LayoutTop: typeof import('./src/components/layouts/LayoutTop.vue')['default']
    MultiSelect: typeof import('./src/components/widgets/MultiSelect.vue')['default']
    MultiSelectBase: typeof import('./src/components/widgets/MultiSelectBase.vue')['default']
    PartialExport: typeof import('./src/components/dialogs/PartialExport.vue')['default']
    PresetLoader: typeof import('./src/components/dialogs/PresetLoader.vue')['default']
    RangeSlider: typeof import('./src/components/widgets/RangeSlider.vue')['default']
    SectionTitle: typeof import('./src/components/sections/SectionTitle.vue')['default']
    SingleSelect: typeof import('./src/components/widgets/SingleSelect.vue')['default']
    SingleSelectBase: typeof import('./src/components/widgets/SingleSelectBase.vue')['default']
    SortSection: typeof import('./src/components/sections/SortSection.vue')['default']
    TextButton: typeof import('./src/components/widgets/TextButton.vue')['default']
    ValueButton: typeof import('./src/components/widgets/ValueButton.vue')['default']
    YasConfigurator: typeof import('./src/components/dialogs/YasConfigurator.vue')['default']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
  }
}
