
var Module = (() => {
  var _scriptDir = import.meta.url;
  
  return (
function(Module) {
  Module = Module || {};


var b;b||(b=typeof Module !== 'undefined' ? Module : {});var m,n;b.ready=new Promise(function(a,c){m=a;n=c});var t=Object.assign({},b),w="object"==typeof window,x="function"==typeof importScripts,z="",A,B,C,fs,D,E;
if("object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node)z=x?require("path").dirname(z)+"/":__dirname+"/",E=()=>{D||(fs=require("fs"),D=require("path"))},A=function(a,c){E();a=D.normalize(a);return fs.readFileSync(a,c?void 0:"utf8")},C=a=>{a=A(a,!0);a.buffer||(a=new Uint8Array(a));return a},B=(a,c,e)=>{E();a=D.normalize(a);fs.readFile(a,function(d,f){d?e(d):c(f.buffer)})},1<process.argv.length&&process.argv[1].replace(/\\/g,"/"),process.argv.slice(2),
process.on("uncaughtException",function(a){throw a;}),process.on("unhandledRejection",function(a){throw a;}),b.inspect=function(){return"[Emscripten Module object]"};else if(w||x)x?z=self.location.href:"undefined"!=typeof document&&document.currentScript&&(z=document.currentScript.src),_scriptDir&&(z=_scriptDir),0!==z.indexOf("blob:")?z=z.substr(0,z.replace(/[?#].*/,"").lastIndexOf("/")+1):z="",A=a=>{var c=new XMLHttpRequest;c.open("GET",a,!1);c.send(null);return c.responseText},x&&(C=a=>{var c=new XMLHttpRequest;
c.open("GET",a,!1);c.responseType="arraybuffer";c.send(null);return new Uint8Array(c.response)}),B=(a,c,e)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?c(d.response):e()};d.onerror=e;d.send(null)};var aa=b.print||console.log.bind(console),F=b.printErr||console.warn.bind(console);Object.assign(b,t);t=null;var G;b.wasmBinary&&(G=b.wasmBinary);var noExitRuntime=b.noExitRuntime||!0;"object"!=typeof WebAssembly&&I("no native wasm support detected");
var J,K=!1;
function ba(a,c,e,d){var f={string:function(h){var p=0;if(null!==h&&void 0!==h&&0!==h){var u=(h.length<<2)+1;p=L(u);var l=p,v=M;if(0<u){u=l+u-1;for(var H=0;H<h.length;++H){var k=h.charCodeAt(H);if(55296<=k&&57343>=k){var pa=h.charCodeAt(++H);k=65536+((k&1023)<<10)|pa&1023}if(127>=k){if(l>=u)break;v[l++]=k}else{if(2047>=k){if(l+1>=u)break;v[l++]=192|k>>6}else{if(65535>=k){if(l+2>=u)break;v[l++]=224|k>>12}else{if(l+3>=u)break;v[l++]=240|k>>18;v[l++]=128|k>>12&63}v[l++]=128|k>>6&63}v[l++]=128|k&63}}v[l]=
0}}return p},array:function(h){var p=L(h.length);N.set(h,p);return p}};a=b["_"+a];var g=[],q=0;if(d)for(var r=0;r<d.length;r++){var y=f[e[r]];y?(0===q&&(q=O()),g[r]=y(d[r])):g[r]=d[r]}e=a.apply(null,g);return e=function(h){0!==q&&P(q);return"string"===c?h?Q(M,h):"":"boolean"===c?!!h:h}(e)}var ca="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function Q(a,c){for(var e=c+NaN,d=c;a[d]&&!(d>=e);)++d;if(16<d-c&&a.buffer&&ca)return ca.decode(a.subarray(c,d));for(e="";c<d;){var f=a[c++];if(f&128){var g=a[c++]&63;if(192==(f&224))e+=String.fromCharCode((f&31)<<6|g);else{var q=a[c++]&63;f=224==(f&240)?(f&15)<<12|g<<6|q:(f&7)<<18|g<<12|q<<6|a[c++]&63;65536>f?e+=String.fromCharCode(f):(f-=65536,e+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else e+=String.fromCharCode(f)}return e}var da,N,M,ea,R;
function fa(){var a=J.buffer;da=a;b.HEAP8=N=new Int8Array(a);b.HEAP16=new Int16Array(a);b.HEAP32=ea=new Int32Array(a);b.HEAPU8=M=new Uint8Array(a);b.HEAPU16=new Uint16Array(a);b.HEAPU32=R=new Uint32Array(a);b.HEAPF32=new Float32Array(a);b.HEAPF64=new Float64Array(a)}var ha,ia=[],ja=[],ka=[];function la(){var a=b.preRun.shift();ia.unshift(a)}var S=0,T=null,U=null;
function I(a){if(b.onAbort)b.onAbort(a);a="Aborted("+a+")";F(a);K=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");n(a);throw a;}function ma(){return V.startsWith("data:application/octet-stream;base64,")}var V;if(b.locateFile){if(V="p2p.wasm",!ma()){var na=V;V=b.locateFile?b.locateFile(na,z):z+na}}else V=(new URL("p2p.wasm",import.meta.url)).toString();
function oa(){var a=V;try{if(a==V&&G)return new Uint8Array(G);if(C)return C(a);throw"both async and sync fetching of the wasm failed";}catch(c){I(c)}}
function qa(){if(!G&&(w||x)){if("function"==typeof fetch&&!V.startsWith("file://"))return fetch(V,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+V+"'";return a.arrayBuffer()}).catch(function(){return oa()});if(B)return new Promise(function(a,c){B(V,function(e){a(new Uint8Array(e))},c)})}return Promise.resolve().then(function(){return oa()})}
function W(a){for(;0<a.length;){var c=a.shift();if("function"==typeof c)c(b);else{var e=c.v;"number"==typeof e?void 0===c.u?ra(e)():ra(e)(c.u):e(void 0===c.u?null:c.u)}}}var X=[];function ra(a){var c=X[a];c||(a>=X.length&&(X.length=a+1),X[a]=c=ha.get(a));return c}
var sa=[null,[],[]],ta={a:function(a,c,e,d){I("Assertion failed: "+(a?Q(M,a):"")+", at: "+[c?c?Q(M,c):"":"unknown filename",e,d?d?Q(M,d):"":"unknown function"])},g:function(){I("")},f:function(a,c,e){M.copyWithin(a,c,c+e)},d:function(a){var c=M.length;a>>>=0;if(2147483648<a)return!1;for(var e=1;4>=e;e*=2){var d=c*(1+.2/e);d=Math.min(d,a+100663296);var f=Math;d=Math.max(a,d);f=f.min.call(f,2147483648,d+(65536-d%65536)%65536);a:{try{J.grow(f-da.byteLength+65535>>>16);fa();var g=1;break a}catch(q){}g=
void 0}if(g)return!0}return!1},e:function(){return 52},c:function(){return 70},b:function(a,c,e,d){for(var f=0,g=0;g<e;g++){var q=R[c>>2],r=R[c+4>>2];c+=8;for(var y=0;y<r;y++){var h=M[q+y],p=sa[a];0===h||10===h?((1===a?aa:F)(Q(p,0)),p.length=0):p.push(h)}f+=r}ea[d>>2]=f;return 0}};
(function(){function a(f){b.asm=f.exports;J=b.asm.h;fa();ha=b.asm.l;ja.unshift(b.asm.i);S--;b.monitorRunDependencies&&b.monitorRunDependencies(S);0==S&&(null!==T&&(clearInterval(T),T=null),U&&(f=U,U=null,f()))}function c(f){a(f.instance)}function e(f){return qa().then(function(g){return WebAssembly.instantiate(g,d)}).then(function(g){return g}).then(f,function(g){F("failed to asynchronously prepare wasm: "+g);I(g)})}var d={a:ta};S++;b.monitorRunDependencies&&b.monitorRunDependencies(S);if(b.instantiateWasm)try{return b.instantiateWasm(d,
a)}catch(f){return F("Module.instantiateWasm callback failed with error: "+f),!1}(function(){return G||"function"!=typeof WebAssembly.instantiateStreaming||ma()||V.startsWith("file://")||"function"!=typeof fetch?e(c):fetch(V,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,d).then(c,function(g){F("wasm streaming compile failed: "+g);F("falling back to ArrayBuffer instantiation");return e(c)})})})().catch(n);return{}})();
b.___wasm_call_ctors=function(){return(b.___wasm_call_ctors=b.asm.i).apply(null,arguments)};b._malloc=function(){return(b._malloc=b.asm.j).apply(null,arguments)};b._free=function(){return(b._free=b.asm.k).apply(null,arguments)};b._p2p_open=function(){return(b._p2p_open=b.asm.m).apply(null,arguments)};b._p2p_close=function(){return(b._p2p_close=b.asm.n).apply(null,arguments)};b._p2p_set_key_seed=function(){return(b._p2p_set_key_seed=b.asm.o).apply(null,arguments)};
b._p2p_decrypt_packet=function(){return(b._p2p_decrypt_packet=b.asm.p).apply(null,arguments)};var O=b.stackSave=function(){return(O=b.stackSave=b.asm.q).apply(null,arguments)},P=b.stackRestore=function(){return(P=b.stackRestore=b.asm.r).apply(null,arguments)},L=b.stackAlloc=function(){return(L=b.stackAlloc=b.asm.s).apply(null,arguments)};b.cwrap=function(a,c,e,d){e=e||[];var f=e.every(function(g){return"number"===g});return"string"!==c&&f&&!d?b["_"+a]:function(){return ba(a,c,e,arguments)}};var Y;
U=function ua(){Y||Z();Y||(U=ua)};
function Z(){function a(){if(!Y&&(Y=!0,b.calledRun=!0,!K)){W(ja);m(b);if(b.onRuntimeInitialized)b.onRuntimeInitialized();if(b.postRun)for("function"==typeof b.postRun&&(b.postRun=[b.postRun]);b.postRun.length;){var c=b.postRun.shift();ka.unshift(c)}W(ka)}}if(!(0<S)){if(b.preRun)for("function"==typeof b.preRun&&(b.preRun=[b.preRun]);b.preRun.length;)la();W(ia);0<S||(b.setStatus?(b.setStatus("Running..."),setTimeout(function(){setTimeout(function(){b.setStatus("")},1);a()},1)):a())}}b.run=Z;
if(b.preInit)for("function"==typeof b.preInit&&(b.preInit=[b.preInit]);0<b.preInit.length;)b.preInit.pop()();Z();


  return Module.ready
}
);
})();
export default Module;